services:
    _defaults:
        autowire: true
        public: true

    Chaplean\Bundle\ElasticsearchBundle\Utility\ElasticsearchUtility:
        arguments: ['%elastic_host%:%elastic_port%', '%chaplean_elasticsearch.indexes%']
